### ISSUE TITLE
Repeated 'Something broke when playing the track.'

### ISSUE THREAD

**Issue by LukeHallett** [lavalink-devs/Lavalink#290]
## Description
Sometimes when I try to play a song it gives me the error 'Something broke when playing the track.' However, it happens randomly on different tracks and playing the track again doesn't reproduce the error.

## Version info
**Client used:** 3.3.1

Output of `java -version`:
```
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

## Logs
```2020-05-12 12:41:13.995 ERROR 29848 --- [back-1-thread-3] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of FXqp9WiFWzc

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.38.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.NullPointerException: null
        at java.base/java.net.URI$Parser.parse(URI.java:3127) ~[na:na]
        at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91) ~[lavaplayer-1.3.38.jar!/:na]
        ... 4 common frames omitted```

**Comment by freyacodes** [comment]
Try using the dev version of Lavalink. It has a newer lavaplayer version, and lavaplayer raises this exception.

**Comment by LukeHallett** [comment]
Alright, I'll try. Thanks.

**Comment by LukeHallett** [comment]
I now don't get any error passed through to the bot, however the track still doesn't play.

```2020-05-12 14:20:39.263 ERROR 22284 --- [back-1-thread-2] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of KdEA5Y3VphA

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.46.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.46.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.46.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.NullPointerException: null
        at java.base/java.net.URI$Parser.parse(URI.java:3127) ~[na:na]
        at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66) ~[lavaplayer-1.3.46.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97) ~[lavaplayer-1.3.46.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87) ~[lavaplayer-1.3.46.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.46.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.46.jar!/:na]
        ... 4 common frames omitted```

**Comment by freyacodes** [comment]
This should be fixed in the latest dev version. I just updated lavaplayer moments ago.

See also https://github.com/sedmelluq/lavaplayer/pull/475

**Comment by LevitatingBusinessMan** [comment]
```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.38.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.NullPointerException: null
        at java.base/java.net.URI$Parser.parse(URI.java:3127) ~[na:na]
        at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91) ~[lavaplayer-1.3.38.jar!/:na]
        ... 4 common frames omitted
```
That's what my logs show.
I am using v3.3.1

**Comment by herrtxbias** [comment]
Hey, I'm still experiencing the same Issue. I'm using the latest dev version from the docker hub.

**Comment by freyacodes** [comment]
@HerrTxbias please show me what this command displays:
```
docker pull fredboat/lavalink:dev && docker run fredboat/lavalink:dev --version
```

**Comment by herrtxbias** [comment]
That's the Output:

```
root@fsn2:/opt/lavalink-server# docker pull fredboat/lavalink:dev && docker run fredboat/lavalink:dev --version
dev: Pulling from fredboat/lavalink
Digest: sha256:0fce34133d2935d177b825808313a248ffc5575f3e3fbf1a2338c25c2a848c2e
Status: Image is up to date for fredboat/lavalink:dev
docker.io/fredboat/lavalink:dev

Version:        ddb5f73b218ca0fc5f494788b282856e3728c6cd-SNAPSHOT
Build:          1052
Build time:     22.05.2020 15:14:34 UTC
Branch          dev
Commit:         ddb5f73
Commit time:    22.05.2020 15:09:21 UTC
JVM:            13.0.2
Lavaplayer      1.3.49
```

**Comment by freyacodes** [comment]
You are on the latest version. Please upload your full lavalink log.

**Comment by herrtxbias** [comment]
Just the part with the error, or the complete one?

The part with the Error:
````
lavalink1_1  | 2020-06-09 21:42:46.356  INFO 1 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"play","guildId":"363391449229950978","track":"QAAAdwIAClJ1aW5pZXJ1bmcAE0Z5bm4gS2xpZW1hbm4gTXVzaWsAAAAAAAKAoAALNkVqRkg5cm1KWk0AAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj02RWpGSDlybUpaTQAHeW91dHViZQAAAAAAAAAA","noReplace":true}
lavalink1_1  | 2020-06-09 21:42:47.261 ERROR 1 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 6EjFH9rmJZM
lavalink1_1  |
lavalink1_1  | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
lavalink1_1  |  at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.38.jar!/:na]
lavalink1_1  |  at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103) ~[lavaplayer-1.3.38.jar!/:na]
lavalink1_1  |  at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.38.jar!/:na]
lavalink1_1  |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
lavalink1_1  |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
lavalink1_1  |  at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
lavalink1_1  | Caused by: java.lang.NullPointerException: null
lavalink1_1  |  at java.base/java.net.URI$Parser.parse(URI.java:3127) ~[na:na]
lavalink1_1  |  at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
lavalink1_1  |  at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66) ~[lavaplayer-1.3.38.jar!/:na]
lavalink1_1  |  at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97) ~[lavaplayer-1.3.38.jar!/:na]
lavalink1_1  |  at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87) ~[lavaplayer-1.3.38.jar!/:na]
lavalink1_1  |  at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.38.jar!/:na]
lavalink1_1  |  at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91) ~[lavaplayer-1.3.38.jar!/:na]
lavalink1_1  |  ... 4 common frames omitted
lavalink1_1  |
lavalink1_1  | 2020-06-09 21:42:47.266  INFO 1 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"stop","guildId":"363391449229950978"}
lavalink1_1  | 2020-06-09 21:42:47.291  INFO 1 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"363391449229950978"}
```

**Comment by freyacodes** [comment]
> ~[lavaplayer-1.3.38.jar!/:na]

This doesn't match your pulled image with `1.3.49`. Please make sure you are actually running the new image. E.g. run `docker-compose up`

I am closing this as the issue is long-resolved. If you still have problems with Docker please reach out on Discord.
